### ISSUE TITLE
ML Model for heart disease detection

### ISSUE THREAD

**Issue by AkUp007** [Rudraps07/Data_Science_Hacktoberfest#1]
Creating a ML model for heart disease detection after analyzing the heart disease dataset.

**Comment by AkUp007** [comment]
can u assign me this issue and add hacktoberfest tag to it?

**Comment by AkUp007** [comment]
@Ryder-07

**Comment by Ryder-07** [comment]
assigned and updated 
kudos!!
also checkout other repos for hacktoberfest and do follow and star the repo

**Comment by Ryder-07** [comment]
issue has been resolved by creating a ML Model for heart disease detection
